// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_rlnXCq8U67VFhuvna890xpKfQjHrNw',
    appId: '1:302631298203:web:ed98bb20220d44f975523e',
    messagingSenderId: '302631298203',
    projectId: 'comunidad-en-movimiento',
    authDomain: 'comunidad-en-movimiento.firebaseapp.com',
    storageBucket: 'comunidad-en-movimiento.firebasestorage.app',
    measurementId: 'G-6KKMJV077W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_qdGdcOMsv_JyULUiKaUHxM2Ogs0bT8',
    appId: '1:302631298203:android:9a4070521bda44d175523e',
    messagingSenderId: '302631298203',
    projectId: 'comunidad-en-movimiento',
    storageBucket: 'comunidad-en-movimiento.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_gpOCItyT5RQoh2C-avH14Z2sI9ms5qA',
    appId: '1:302631298203:ios:f8642b220f1a131b75523e',
    messagingSenderId: '302631298203',
    projectId: 'comunidad-en-movimiento',
    storageBucket: 'comunidad-en-movimiento.firebasestorage.app',
    iosBundleId: 'com.example.comunidadEnMovimiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_gpOCItyT5RQoh2C-avH14Z2sI9ms5qA',
    appId: '1:302631298203:ios:f8642b220f1a131b75523e',
    messagingSenderId: '302631298203',
    projectId: 'comunidad-en-movimiento',
    storageBucket: 'comunidad-en-movimiento.firebasestorage.app',
    iosBundleId: 'com.example.comunidadEnMovimiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_rlnXCq8U67VFhuvna890xpKfQjHrNw',
    appId: '1:302631298203:web:299f7c382673216f75523e',
    messagingSenderId: '302631298203',
    projectId: 'comunidad-en-movimiento',
    authDomain: 'comunidad-en-movimiento.firebaseapp.com',
    storageBucket: 'comunidad-en-movimiento.firebasestorage.app',
    measurementId: 'G-BJYC6WMK72',
  );
}
