// TODO EN UNA STRING
String traducir(String texto, String idiomaSeleccionado) {
  // Si el idioma es español, devolvemos el texto original.
  if (idiomaSeleccionado == 'es') return texto;

  Map<String, Map<String, String>> traducciones = {
    'en': {
      'Nueva incidencia:': 'New incident:',
      'Los servicios de ubicación están deshabilitados.': 'Location services are disabled.',
      'Permiso de ubicación denegado.': 'Location permission denied.',
      'Permiso de ubicación denegado permanentemente.': 'Location permission permanently denied.',
      'Error al obtener la ubicación:': 'Error getting location:',
      'No se ha obtenido tu ubicación actual.': 'Your current location was not obtained.',
      'Mi Ubicación': 'My Location',
      'Selecciona origen y destino antes de iniciar la ruta.': 'Select origin and destination before starting the route.',
      'Error al obtener la ruta:': 'Error getting the route:',
      'Menos de un minuto': 'Less than a minute',
      'horas': 'hours',
      'minutos': 'minutes',
      'Ubicación Origen': 'Origin Location',
      'Ubicación Destino': 'Destination Location',
      'Iniciar Ruta': 'Start Route',
      'Volver': 'Back',
      'Abrir Mapa': 'Open Map',
      'Configuración': 'Settings',
      'Tipo de incidencia': 'Type of incident',
      'Descripción (opcional)': 'Description (optional)',
      'Cancelar': 'Cancel',
      'Aceptar': 'OK',
      'Añadir incidencia': 'Add incident',
      'Incidencia:': 'Incident:',
      'Descripción:': 'Description:',
      '¿Eliminar esta incidencia?': 'Delete this incident?',
      'Filtrar Incidencias': 'Filter Incidents',
      'Listado Incidencias Cercanas': 'List Nearby Incidents',
      'Filtrar por tipo': 'Filter by type',
      'Tipo': 'Type',
      'Todos': 'All',
      'Cerrar': 'Close',
      'Incidencias Cercanas': 'Nearby Incidents',
      'Distancia:': 'Distance:',
      'Configuración Daltonismo': 'Color Blindness Settings',
      'Modo': 'Mode',
      'Por defecto': 'Default',
      'Idioma': 'Language',
      'Incidencia tipo': 'Incident type',
      'Seleccionar destino en el mapa': 'Select destination on map',
      'Haz click en el mapa para añadir una incidencia.': 'Click on the map to add an incident.',
      'Haz click en el mapa para seleccionar el destino.': 'Click on the map to select the destination.',
      'Tiempo estimado:': 'Estimated time:',
      'Ocultar Incidencias': 'Hide Incidents',
      'Mostrar Incidencias': 'Show Incidents',
      'Tu Ubicación': 'Your Location',
      'Cargando ubicación...': 'Loading location...',
      'Categoría de Accesibilidad': 'Accessibility Category',
      'Sin problema': 'No problem',
      'Leve': 'Light',
      'Moderado': 'Moderate',
      'Grave': 'Severe',
      'Tipo de Superficie': 'Surface Type',
      'Acera': 'Sidewalk',
      'Calzada': 'Road',
      'Otro': 'Other',
      'Información Adicional (opcional)': 'Additional Information (optional)',
      'Sin información adicional': 'No additional information',
      'Sí, evitar peligro': 'Yes, avoid danger',
      'No': 'No',
      'Peligro detectado en la ruta': 'Danger detected on the route',
      'Se ha detectado un tramo peligroso en la ruta. ¿Deseas recalcular la ruta para evitarlo?':
          'A dangerous section has been detected on the route. Do you want to recalculate the route to avoid it?',
      'Ruta recalculada con éxito evitando el punto peligroso.':
          'Route successfully recalculated avoiding the dangerous point.',
      'Error al recalcular la ruta:': 'Error recalculating the route:',
      'No se puede recalcular la ruta sin origen y destino definidos.':
          'Cannot recalculate the route without defined origin and destination.',
      'Error al seleccionar la ubicación:': 'Error selecting location:',
      'Error al cargar los modelos:': 'Error loading models:',
      'Ocurrió un error al mostrar la predicción:':
          'An error occurred while displaying the prediction:',
      'Por favor, selecciona origen y destino antes de ver la predicción.':
          'Please select origin and destination before viewing the prediction.',
      'Los modelos aún se están cargando. Por favor, espera un momento.':
          'The models are still loading. Please wait a moment.',
      'Tramo': 'Segment',
      'Probabilidad general de incidencia:': 'Overall probability of incident:',
      'Detalles de tramos peligrosos:': 'Details of dangerous segments:',
      'Ocultar Escaleras': 'Hide Stairs',
      'Mostrar Escaleras': 'Show Stairs',
      'Limpiar Ruta': 'Clear Route',
      'Cerrar Sesión': 'Sign Out',
      'Ver Predicción': 'View Prediction',
      'Predicción de Incidencias': 'Incident Prediction',
      'Desglosar predicción': 'Breakdown prediction',
      'Tramos Peligrosos (vista 3D)': 'Dangerous Segments (3D view)',
      'Orientar': 'Align',
      'Predecir Ruta': 'Predict Route',
      // clima
      'Cargando datos del clima...': 'Loading weather data...',
      'Error al cargar datos del clima': 'Error loading weather data',
      'Reintentar': 'Retry',
      'Viento': 'Wind',
      'Previsión de lluvia:': 'Rain forecast:',
      'y más': 'and more',
      'Pronóstico': 'Forecast',
      'Historial': 'History',
      'Pronóstico de 7 días': '7-day forecast',
      'No hay datos históricos disponibles': 'No historical data available',
      'Historial de Clima': 'Weather History',
      'Ciudad no disponible': 'City not available',
      // Condiciones climáticas
      'Despejado': 'Clear',
      'Bruma': 'Haze',
      'Neblina': 'Mist',
      'Lluvia ligera': 'Light rain',
      'Tormenta de arena': 'Sandstorm',
      'Niebla': 'Fog',
      'Llovizna': 'Drizzle',
      'Lluvia': 'Rain',
      'Nieve': 'Snow',
      'Tormenta': 'Storm',
      'Tormenta fuerte': 'Heavy storm',
      'Desconocido': 'Unknown',
      // Recomendaciones de clima
      'Hace mucho calor! Mantente hidratado y en la sombra.': 'It\'s very hot! Stay hydrated and in the shade.',
      'Hace calor! Usa protector solar.': 'It\'s hot! Use sunscreen.',
      'Clima agradable, perfecto para salir.': 'Pleasant weather, perfect to go out.',
      'Clima templado, una chaqueta ligera es recomendable.': 'Mild weather, a light jacket is recommended.',
      'Hace algo de frío, abrígate.': 'It\'s a bit cold, dress warmly.',
      'Hace frío! Abrígate bien.': 'It\'s cold! Dress up warm.',
      'Hace mucho frío! Usa varias capas de ropa.': 'It\'s very cold! Wear several layers of clothing.',
      // Traducciones para el chatbot (el mensaje bienvenida)
      'Chatea conmigo': 'Chat with me',
      'Enviar': 'Send',
      'Escribe tu mensaje...': 'Type your message...',
      'Asistente IA': 'AI Assistant',
      'Estoy aquí para ayudarte': 'I\'m here to help you',
    },
    'fr': {
      'Nueva incidencia:': 'Nouvel incident :',
      'Los servicios de ubicación están deshabilitados.': 'Les services de localisation sont désactivés.',
      'Permiso de ubicación denegado.': 'Autorisation de localisation refusée.',
      'Permiso de ubicación denegado permanentemente.': 'Autorisation de localisation refusée de façon permanente.',
      'Error al obtener la ubicación:': 'Erreur lors de l\'obtention de la localisation :',
      'No se ha obtenido tu ubicación actual.': 'Votre position actuelle n\'a pas été obtenue.',
      'Mi Ubicación': 'Ma position',
      'Selecciona origen y destino antes de iniciar la ruta.': 'Sélectionnez l\'origine et la destination avant de démarrer l\'itinéraire.',
      'Error al obtener la ruta:': 'Erreur lors de l\'obtention de l\'itinéraire :',
      'Menos de un minuto': 'Moins d\'une minute',
      'horas': 'heures',
      'minutos': 'minutes',
      'Ubicación Origen': 'Point de départ',
      'Ubicación Destino': 'Point d\'arrivée',
      'Iniciar Ruta': 'Démarrer l\'itinéraire',
      'Volver': 'Retour',
      'Abrir Mapa': 'Ouvrir la carte',
      'Configuración': 'Paramètres',
      'Tipo de incidencia': 'Type d\'incident',
      'Descripción (opcional)': 'Description (facultative)',
      'Cancelar': 'Annuler',
      'Aceptar': 'OK',
      'Añadir incidencia': 'Ajouter un incident',
      'Incidencia:': 'Incident :',
      'Descripción:': 'Description :',
      '¿Eliminar esta incidencia?': 'Supprimer cet incident ?',
      'Filtrar Incidencias': 'Filtrer les incidents',
      'Listado Incidencias Cercanas': 'Liste des incidents à proximité',
      'Filtrar por tipo': 'Filtrer par type',
      'Tipo': 'Type',
      'Todos': 'Tous',
      'Cerrar': 'Fermer',
      'Incidencias Cercanas': 'Incidents à proximité',
      'Distancia:': 'Distance :',
      'Configuración Daltonismo': 'Paramètres daltonisme',
      'Modo': 'Mode',
      'Por defecto': 'Par défaut',
      'Idioma': 'Langue',
      'Incidencia tipo': 'Type d\'incident',
      'Seleccionar destino en el mapa': 'Sélectionner la destination sur la carte',
      'Haz click en el mapa para añadir una incidencia.': 'Cliquez sur la carte pour ajouter un incident.',
      'Haz click en el mapa para seleccionar el destino.': 'Cliquez sur la carte pour sélectionner la destination.',
      'Tiempo estimado:': 'Temps estimé :',
      'Ocultar Incidencias': 'Masquer les incidents',
      'Mostrar Incidencias': 'Afficher les incidents',
      'Tu Ubicación': 'Votre position',
      'Cargando ubicación...': 'Chargement de la localisation...',
      'Categoría de Accesibilidad': 'Catégorie d\'accessibilité',
      'Sin problema': 'Sans problème',
      'Leve': 'Léger',
      'Moderado': 'Modéré',
      'Grave': 'Sévère',
      'Tipo de Superficie': 'Type de surface',
      'Acera': 'Trottoir',
      'Calzada': 'Chaussée',
      'Otro': 'Autre',
      'Información Adicional (opcional)': 'Informations complémentaires (facultatives)',
      'Sin información adicional': 'Aucune information complémentaire',
      'Sí, evitar peligro': 'Oui, éviter le danger',
      'No': 'Non',
      'Peligro detectado en la ruta': 'Danger détecté sur l\'itinéraire',
      'Se ha detectado un tramo peligroso en la ruta. ¿Deseas recalcular la ruta para evitarlo?':
          'Une section dangereuse a été détectée sur l\'itinéraire. Voulez-vous recalculer l\'itinéraire pour l\'éviter ?',
      'Ruta recalculada con éxito evitando el punto peligroso.':
          'Itinéraire recalculé avec succès en évitant le point dangereux.',
      'Error al recalcular la ruta:': 'Erreur lors du recalcul de l\'itinéraire :',
      'No se puede recalcular la ruta sin origen y destino definidos.':
          'Impossible de recalculer l\'itinéraire sans origine et destination définies.',
      'Error al seleccionar la ubicación:': 'Erreur lors de la sélection de la localisation :',
      'Error al cargar los modelos:': 'Erreur lors du chargement des modèles :',
      'Ocurrió un error al mostrar la predicción:':
          'Une erreur est survenue lors de l\'affichage de la prédiction :',
      'Por favor, selecciona origen y destino antes de ver la predicción.':
          'Veuillez sélectionner l\'origine et la destination avant de voir la prédiction.',
      'Los modelos aún se están cargando. Por favor, espera un momento.':
          'Les modèles sont en cours de chargement. Veuillez patienter un instant.',
      'Tramo': 'Segment',
      'Probabilidad general de incidencia:': 'Probabilité globale d\'incident :',
      'Detalles de tramos peligrosos:': 'Détails des segments dangereux :',
      'Ocultar Escaleras': 'Masquer les escaliers',
      'Mostrar Escaleras': 'Afficher les escaliers',
      'Limpiar Ruta': 'Effacer la route',
      'Cerrar Sesión': 'Déconnexion',
      'Ver Predicción': 'Voir la prédiction',
      'Predicción de Incidencias': 'Prédiction des incidents',
      'Desglosar predicción': 'Décomposer la prédiction',
      'Tramos Peligrosos (vista 3D)': 'Segments dangereux (vue 3D)',
      'Orientar': 'Orienter',
      'Predecir Ruta': 'Prédire l\'itinéraire',
      // Clima
      'Cargando datos del clima...': 'Chargement des données météo...',
      'Error al cargar datos del clima': 'Erreur lors du chargement des données météo',
      'Reintentar': 'Réessayer',
      'Viento': 'Vent',
      'Previsión de lluvia:': 'Prévisions de pluie:',
      'y más': 'et plus',
      'Pronóstico': 'Prévisions',
      'Historial': 'Historique',
      'Pronóstico de 7 días': 'Prévisions sur 7 jours',
      'No hay datos históricos disponibles': 'Aucune donnée historique disponible',
      'Historial de Clima': 'Historique météo',
      'Ciudad no disponible': 'Ville non disponible',
      // Condiciones climáticas
      'Despejado': 'Dégagé',
      'Bruma': 'Brume',
      'Neblina': 'Brouillard léger',
      'Lluvia ligera': 'Pluie légère',
      'Tormenta de arena': 'Tempête de sable',
      'Niebla': 'Brouillard',
      'Llovizna': 'Bruine',
      'Lluvia': 'Pluie',
      'Nieve': 'Neige',
      'Tormenta': 'Orage',
      'Tormenta fuerte': 'Orage violent',
      'Desconocido': 'Inconnu',
      // Recomendaciones de clima
      'Hace mucho calor! Mantente hidratado y en la sombra.': 'Il fait très chaud! Restez hydraté et à l\'ombre.',
      'Hace calor! Usa protector solar.': 'Il fait chaud! Utilisez de la crème solaire.',
      'Clima agradable, perfecto para salir.': 'Temps agréable, parfait pour sortir.',
      'Clima templado, una chaqueta ligera es recomendable.': 'Temps doux, une veste légère est recommandée.',
      'Hace algo de frío, abrígate.': 'Il fait un peu froid, couvrez-vous.',
      'Hace frío! Abrígate bien.': 'Il fait froid! Couvrez-vous bien.',
      'Hace mucho frío! Usa varias capas de ropa.': 'Il fait très froid! Portez plusieurs couches de vêtements.',
      // Traducciones para el chatbot
      'Chatea conmigo': 'Discutez avec moi',
      'Enviar': 'Envoyer',
      'Escribe tu mensaje...': 'Écrivez votre message...',
      'Asistente IA': 'Assistant IA',
      'Estoy aquí para ayudarte': 'Je suis là pour vous aider',
    },
    'de': {
      'Nueva incidencia:': 'Neuer Vorfall:',
      'Los servicios de ubicación están deshabilitados.': 'Standortdienste sind deaktiviert.',
      'Permiso de ubicación denegado.': 'Standortzugriff verweigert.',
      'Permiso de ubicación denegado permanentemente.': 'Standortzugriff dauerhaft verweigert.',
      'Error al obtener la ubicación:': 'Fehler beim Abrufen des Standorts:',
      'No se ha obtenido tu ubicación actual.': 'Ihr aktueller Standort wurde nicht ermittelt.',
      'Mi Ubicación': 'Mein Standort',
      'Selecciona origen y destino antes de iniciar la ruta.': 'Wählen Sie Start und Ziel, bevor Sie die Route starten.',
      'Error al obtener la ruta:': 'Fehler beim Abrufen der Route:',
      'Menos de un minuto': 'Weniger als eine Minute',
      'horas': 'Stunden',
      'minutos': 'Minuten',
      'Ubicación Origen': 'Startort',
      'Ubicación Destino': 'Zielort',
      'Iniciar Ruta': 'Route starten',
      'Volver': 'Zurück',
      'Abrir Mapa': 'Karte öffnen',
      'Configuración': 'Einstellungen',
      'Tipo de incidencia': 'Vorfalltyp',
      'Descripción (opcional)': 'Beschreibung (optional)',
      'Cancelar': 'Abbrechen',
      'Aceptar': 'OK',
      'Añadir incidencia': 'Vorfall hinzufügen',
      'Incidencia:': 'Vorfall:',
      'Descripción:': 'Beschreibung:',
      '¿Eliminar esta incidencia?': 'Diesen Vorfall löschen?',
      'Filtrar Incidencias': 'Vorfälle filtern',
      'Listado Incidencias Cercanas': 'Liste nahegelegener Vorfälle',
      'Filtrar por tipo': 'Nach Typ filtern',
      'Tipo': 'Typ',
      'Todos': 'Alle',
      'Cerrar': 'Schließen',
      'Incidencias Cercanas': 'Nahe Vorfälle',
      'Distancia:': 'Entfernung:',
      'Configuración Daltonismo': 'Farbsehschwäche Einstellungen',
      'Modo': 'Modus',
      'Por defecto': 'Standard',
      'Idioma': 'Sprache',
      'Incidencia tipo': 'Vorfalltyp',
      'Seleccionar destino en el mapa': 'Ziel auf der Karte auswählen',
      'Haz click en el mapa para añadir una incidencia.': 'Klicken Sie auf die Karte, um einen Vorfall hinzuzufügen.',
      'Haz click en el mapa para seleccionar el destino.': 'Klicken Sie auf die Karte, um das Ziel auszuwählen.',
      'Tiempo estimado:': 'Geschätzte Zeit:',
      'Ocultar Incidencias': 'Vorfälle ausblenden',
      'Mostrar Incidencias': 'Vorfälle anzeigen',
      'Tu Ubicación': 'Ihr Standort',
      'Cargando ubicación...': 'Standort wird geladen...',
      'Categoría de Accesibilidad': 'Barrierefreiheitskategorie',
      'Sin problema': 'Kein Problem',
      'Leve': 'Leicht',
      'Moderado': 'Mäßig',
      'Grave': 'Schwer',
      'Tipo de Superficie': 'Oberflächentyp',
      'Acera': 'Bürgersteig',
      'Calzada': 'Fahrbahn',
      'Otro': 'Andere',
      'Información Adicional (opcional)': 'Zusätzliche Informationen (optional)',
      'Sin información adicional': 'Keine zusätzlichen Informationen',
      'Sí, evitar peligro': 'Ja, Gefahr vermeiden',
      'No': 'Nein',
      'Peligro detectado en la ruta': 'Gefahr auf der Route erkannt',
      'Se ha detectado un tramo peligroso en la ruta. ¿Deseas recalcular la ruta para evitarlo?':
          'Ein gefährlicher Streckenabschnitt wurde auf der Route erkannt. Möchten Sie die Route neu berechnen, um ihn zu vermeiden?',
      'Ruta recalculada con éxito evitando el punto peligroso.':
          'Route erfolgreich neu berechnet und gefährlichen Bereich vermieden.',
      'Error al recalcular la ruta:': 'Fehler bei der Neuberechnung der Route:',
      'No se puede recalcular la ruta sin origen y destino definidos.':
          'Die Route kann nicht neu berechnet werden, ohne dass Start und Ziel definiert sind.',
      'Error al seleccionar la ubicación:': 'Fehler bei der Standortauswahl:',
      'Error al cargar los modelos:': 'Fehler beim Laden der Modelle:',
      'Ocurrió un error al mostrar la predicción:':
          'Beim Anzeigen der Vorhersage ist ein Fehler aufgetreten:',
      'Por favor, selecciona origen y destino antes de ver la predicción.':
          'Bitte wählen Sie Start und Ziel, bevor Sie die Vorhersage anzeigen.',
      'Los modelos aún se están cargando. Por favor, espera un momento.':
          'Die Modelle werden noch geladen. Bitte warten Sie einen Moment.',
      'Tramo': 'Segment',
      'Probabilidad general de incidencia:': 'Gesamtwahrscheinlichkeit eines Vorfalls:',
      'Detalles de tramos peligrosos:': 'Details gefährlicher Segmente:',
      'Ocultar Escaleras': 'Treppen ausblenden',
      'Mostrar Escaleras': 'Treppen anzeigen',
      'Limpiar Ruta': 'Route löschen',
      'Cerrar Sesión': 'Abmelden',
      'Ver Predicción': 'Vorhersage anzeigen',
      'Predicción de Incidencias': 'Vorhersage von Vorfällen',
      'Desglosar predicción': 'Vorhersage aufschlüsseln',
      'Tramos Peligrosos (vista 3D)': 'Gefährliche Segmente (3D-Ansicht)',
      'Orientar': 'Ausrichten',
      'Predecir Ruta': 'Route vorhersagen',
      // Clima
      'Cargando datos del clima...': 'Wetterdaten werden geladen...',
      'Error al cargar datos del clima': 'Fehler beim Laden der Wetterdaten',
      'Reintentar': 'Wiederholen',
      'Viento': 'Wind',
      'Previsión de lluvia:': 'Regenvorhersage:',
      'y más': 'und mehr',
      'Pronóstico': 'Vorhersage',
      'Historial': 'Verlauf',
      'Pronóstico de 7 días': '7-Tage-Vorhersage',
      'No hay datos históricos disponibles': 'Keine historischen Daten verfügbar',
      'Historial de Clima': 'Wetterverlauf',
      'Ciudad no disponible': 'Stadt nicht verfügbar',
      // Condiciones climáticas
      'Despejado': 'Klar',
      'Bruma': 'Dunst',
      'Neblina': 'Nebel',
      'Lluvia ligera': 'Leichter Regen',
      'Tormenta de arena': 'Sandsturm',
      'Niebla': 'Nebel',
      'Llovizna': 'Nieselregen',
      'Lluvia': 'Regen',
      'Nieve': 'Schnee',
      'Tormenta': 'Gewitter',
      'Tormenta fuerte': 'Starkes Gewitter',
      'Desconocido': 'Unbekannt',
      // Recomendaciones de clima
      'Hace mucho calor! Mantente hidratado y en la sombra.': 'Es ist sehr heiß! Bleiben Sie hydratisiert und im Schatten.',
      'Hace calor! Usa protector solar.': 'Es ist heiß! Verwenden Sie Sonnenschutz.',
      'Clima agradable, perfecto para salir.': 'Angenehmes Wetter, perfekt zum Ausgehen.',
      'Clima templado, una chaqueta ligera es recomendable.': 'Mildes Wetter, eine leichte Jacke wird empfohlen.',
      'Hace algo de frío, abrígate.': 'Es ist etwas kalt, ziehen Sie sich warm an.',
      'Hace frío! Abrígate bien.': 'Es ist kalt! Ziehen Sie sich warm an.',
      'Hace mucho frío! Usa varias capas de ropa.': 'Es ist sehr kalt! Tragen Sie mehrere Kleidungsschichten.',
      // Traducciones para el chatbot
      'Chatea conmigo': 'Chatte mit mir',
      'Enviar': 'Senden',
      'Escribe tu mensaje...': 'Schreiben Sie Ihre Nachricht...',
      'Asistente IA': 'KI-Assistent',
      'Estoy aquí para ayudarte': 'Ich bin hier, um zu helfen',
    },
  };

  if (!traducciones.containsKey(idiomaSeleccionado)) return texto;
  return traducciones[idiomaSeleccionado]?[texto] ?? texto;
}